version: "2"

services:
  sut:
    container_name: machinery_sut
    image: machinery_sut:latest
    volumes:
      - "./:/go/src/github.com/RichardKnop/machinery/v2"
    depends_on:
      - rabbitmq
      - redis
    links:
      - rabbitmq
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      AMQP_URLS: 'amqp://guest:guest@dummy:5672/,amqp://guest:guest@rabbitmq:5672/'
      AMQP_URLS_SEPARATOR: ','
      REDIS_URL: 'redis:6379'
      SQS_URL: ${SQS_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_REGION: 'us-west-2'

  rabbitmq:
    container_name: machinery_sut_rabbitmq
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    logging:
      driver: none

  redis:
    container_name: machinery_sut_redis
    image: redis
    logging:
      driver: none
